jinengandhi-intel/graphene_local_ci

- ci/ubuntu18.04.dockerfile
- ci/ubuntu20.04.dockerfile
In this commit, proxy is updated in docker files for 18.04 and 20.04.
> Updating the proxy in Docker files

- ci/stage-build-nosgx.jenkinsfile
- ci/stage-build-sgx.jenkinsfile
In this commit, changes corresponding to upcoming PR #71 has been made.
> Changes corresponding to PR #71

- ltp_config/runltp_tests.py
In this commit, if the negative time drift is detected below 50 ms, it is considered as pass for woken up early issue
> Checking condition for negative time drift in parser

- ci/config-docker.jenkinsfile
In this commit, the changes are made to docker file corresponding to seccomp policy
> Adding custom Docker seccomp policy

- ltp_config/update_manifest.sh
In this commit, the LTP manifest for some TCs are updated according to new format for SGX allowed files
> Updating sed commands for some TCs in LTP manifest

- ltp_config/ltp_tests.cfg
In this commit, the above mentioned testcases are enabled in config file
> Enabling sendfile02 and sendfile06

- ci/linux-direct-ubuntu21.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
- ci/ubuntu21.04.dockerfile
In this commit, Ubuntu 21.04 docker file and jenkinsfile have been added to enable job with Ubuntu 21.04 on CI.
> Adding dockerfile and jenkinsfile for Ubuntu 21.04

- ci/config-docker.jenkinsfile
- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/stage-test-direct.jenkinsfile
- ci/stage-test-sgx.jenkinsfile
- ci/ubuntu18.04.dockerfile
- ci/ubuntu20.04.dockerfile
- go_helloworld/Makefile
- go_helloworld/helloworld.go
- go_helloworld/helloworld.manifest.template
- test_workloads.py
In this commit, go_helloworld is enabled on servers.
> Adding go_helloworld example for servers

- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/stage-build-nosgx.jenkinsfile
- ci/stage-build-sgx.jenkinsfile
- ci/stage-test.jenkinsfile
- ci/ubuntu18.04.dockerfile
- ci/ubuntu20.04.dockerfile
- ci/ubuntu21.04.dockerfile
In this commit, musl is enabled and LibOS suite is run twice.
> Adding musl support

- ltp_config/ltp_tests.cfg
- ltp_src/testcases/kernel/syscalls/mlock/mlock04.c
In this commit, mlock, mlock2, munlock, mlockall and munlockall syscalls are added.
> Adding mlock testcases

- ci/centos8.dockerfile
- ci/linux-direct-centos8-docker-gcc-release.jenkinsfile
- ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
- ltp_config/manifest.LTP
- ltp_config/manifest.template
In this commit, dockerfile for CentOS is added to execute pipeline inside a container.
> CentOS dockerfile

- ltp_config/test_ltp.py
In this commit, the parser is amended to check the must pass condition.
> Amending the LTP parser

- ci/stage-test.jenkinsfile
In this commit, the results for above mentioned suites are archived for better debugging.
> Archiving LibOS, PAL and FS results

- ltp_config/ltp_tests.cfg
In this commit, the above mentioned testcases are enabled.
> Unskipping sendfile02_64 and sendfile06_64

- Patch/rename_protected_files.patch
- ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
- ci/stage-build-sgx.jenkinsfile
In this commit, a testcase to check renaming of protected files for SGX configuration has been added in FS suite.
> Adding testcase to check renaming of protected files for SGX

- ltp_config/ltp_tests.cfg
In this commit, epoll01 is enabled in LTP suite after the commit "[LibOS] Rework epoll implementation".
> Enabling epoll01

- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu21.04-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
In this commit, the jobs are triggered with the above mentioned commit.
> Checking out "Refactor sysfs to improve sanitization"

- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu21.04-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
In this commit, checking out is amended for sysfs branch.
> Amending branch checkout

- ltp_config/manifest.template
In this commit, the files that were added for pipe2_02 are removed.
> Reverting the changes required for pipe2_02

- ci/stage-build-nosgx.jenkinsfile
- ci/stage-build-sgx.jenkinsfile
In this commit, meson is built with werror flag by default.
> Build meson with werror option by default

- ltp_config/manifest_18_04.template
- ltp_config/manifest_20_04_21_04.template
- ltp_config/manifest_CentOS_RHEL.template
In this commit, FS mounting is carried out as per the new format.
> Updating format for mounting FS for LTP suite

- ci/linux-direct-ubuntu21.10-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.10-gcc-release.jenkinsfile
- ci/stage-build-nosgx.jenkinsfile
- ci/stage-build-sgx.jenkinsfile
- ci/ubuntu21.10.dockerfile
In this commit, dockerfile for Ubuntu 21.10 is added and meson command to build Gramine is also updated.
> Adding Ubuntu 21.10 configuration and meson build changes

- ci/linux-perf-tf-bert.jenkinsfile
- ci/linux-perf-tf-resnet.jenkinsfile
- ci/stage-build-perf.jenkinsfile
- ci/stage-tf-bert-perf.jenkinsfile
- ci/stage-tf-resnet-perf.jenkinsfile
In this commit, BERT and ResNet examples are enabled.
> Adding BERT and ResNet examples

- ci/linux-perf-tf-bert.jenkinsfile
- ci/linux-perf-tf-resnet.jenkinsfile
- ci/stage-build-perf.jenkinsfile
- ci/stage-tf-bert-perf.jenkinsfile
- ci/stage-tf-resnet-perf.jenkinsfile
- perf_benchmarking/bert/Makefile
- perf_benchmarking/bert/python.manifest.template
- perf_benchmarking/bert/start_benchmark.sh
- perf_benchmarking/resnet/Makefile
- perf_benchmarking/resnet/python.manifest.template
- perf_benchmarking/resnet/start_benchmark.sh
- tf_parser.py
In this commit, the BERT and RESNET pipelines are made parameterised.
> Adding CI parameters to BERT and RESNET pipelines

- ci/stage-test-sgx.jenkinsfile
In this commit, LTP suite is enabled for after reflashing OOT machine.
> Enabling LTP suite for OOT

- ci/linux-perf-tf-bert.jenkinsfile
- ci/linux-perf-tf-resnet.jenkinsfile
- ci/stage-tf-bert-perf.jenkinsfile
- ci/stage-tf-resnet-perf.jenkinsfile
- perf_benchmarking/bert/python.manifest.template
- perf_benchmarking/bert/start_benchmark.sh
- perf_benchmarking/resnet/python.manifest.template
- perf_benchmarking/resnet/start_benchmark.sh
In this commit, the TF branch is updated and results are directed towards a text file for better performance.
> Updating TF branch and directing the results to text file

- ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/stage-test-examples.jenkinsfile
- ci/ubuntu18.04.dockerfile
- ci/ubuntu20.04.dockerfile
- test_workloads.py
- utils/openvino_setup.sh
Gramine-Native Jenkins Run:
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/83/consoleFull
> Add OpenVino Example into local CI

- ci/linux-sgx-gsc-release.jenkinsfile
- ci/stage-test-gsc-python.jenkinsfile
- gsc/templates/centos/Dockerfile.build.template
- gsc/templates/centos/Dockerfile.compile.template
- gsc/templates/ubuntu/Dockerfile.build.template
- gsc/templates/ubuntu/Dockerfile.compile.template
- gsc/test/python.dockerfile
- gsc/test/python.manifest
In this commit, python example is enabled for GSC.
> Enabling GSC Python example

- ltp_config/ltp_tests.cfg
In this commit, some fallocate testcases are enabled corresponding to recent Gramine master commit.
> Add simple fallocate syscall implementation

- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/stage-test-examples.jenkinsfile
- test_workloads.py
S.No | Machine | Gnative | GSGX
-- | -- | -- | --
1 | graphene_centos_8_5.14 | http://ba5sapp0350:8080/job/anjali_graphene_native_centos/14/consoleFull | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/15/console
2 | graphene_icl_centos8_5.13 | http://ba5sapp0350:8080/job/anjali_graphene_native_centos/16/console |  
3 | graphene_icl_rhel8 |   | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/19/console
4 | graphene_icl_rhel_client |   | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/14/console
> Enable Gramine Examples for CentOS

- ci/config-docker.jenkinsfile
- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/stage-test-direct.jenkinsfile
- ci/stage-test-examples.jenkinsfile
- ci/stage-test-sgx.jenkinsfile
- test_workloads.py
- utils/openvino_setup.sh
  | Gnative |   |  
-- | -- | -- | --
1 | graphene_icl_rhel_client | http://ba5sapp0350:8080/job/anjali_graphene_native_centos/34 |  
2 | graphene_centos_8_5.14 | http://ba5sapp0350:8080/job/anjali_graphene_native_centos/33/console |  
3 | graphene_18.04_5.16 | http://ba5sapp0350:8080/job/anjali_gnative_ubuntu/88/console |  
  |   |   |  
  |   |   |  
  | GSGX |   |  
4 | graphene_icl_rhel8 | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/37 |  
5 | graphene_icl_rhel_client | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/34 |  
6 | graphene_icl_centos8_5.13 | http://ba5sapp0350:8080/job/anjali_graphene_sgx_centos/35 |  
7 | graphene_icl_04 | http://ba5sapp0350:8080/job/anjali_gsgx_ubuntu/45 |  
> Enabling OpenVino for RHEL

- ci/centos8.dockerfile
- ci/config-centos8.jenkinsfile
- ci/config-docker.jenkinsfile
- ci/linux-direct-centos8-docker-gcc-release.jenkinsfile
- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/stage-test-direct.jenkinsfile
- ci/stage-test-examples.jenkinsfile
- ci/stage-test-sgx.jenkinsfile
- test_workloads.py
  | Gnative |  
-- | -- | --
1 | graphene_icl_rhel_client | http://ba5sapp0350:8080/job/anjali_gnative_centos/40/
2 | graphene_centos_8_5.14 | http://ba5sapp0350:8080/job/anjali_docker_gnative_centos/1
3 | graphene_18.04_5.16 | http://ba5sapp0350:8080/job/anjali_gnative_ubuntu/90
4 | graphene_icl_dcap | http://ba5sapp0350:8080/job/anjali_gnative_ubuntu/91/console
  |   |  
  | GSGX |  
5 | graphene_icl_rhel8 | http://ba5sapp0350:8080/job/anjali_gsgx_centos/46/
6 | graphene_icl_centos8_5.13 | http://ba5sapp0350:8080/job/anjali_docker_gsgx_centos/21/
7 | graphene_icl_04 | http://ba5sapp0350:8080/job/anjali_gsgx_ubuntu/47
8 | graphene_icl_dcap | http://ba5sapp0350:8080/job/anjali_gsgx_ubuntu/51
9 | graphene_centos_8_5.14 | http://ba5sapp0350:8080/job/anjali_docker_gsgx_centos/3
10 | …
> Enable CentOS example for docker image

- ci/centos8.dockerfile
- ci/linux-direct-centos8-docker-gcc-release.jenkinsfile
- ci/linux-direct-centos8.2-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu21.04-gcc-release.jenkinsfile
- ci/linux-direct-ubuntu21.10-gcc-release.jenkinsfile
- ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
- ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
- ci/linux-sgx-ubuntu21.10-gcc-release.jenkinsfile
- ci/stage-test-direct.jenkinsfile
- ci/stage-test-sandstone.jenkinsfile
- ci/stage-test-sgx.jenkinsfile
- ci/stage-verification-examples.jenkinsfile
- ci/ubuntu18.04.dockerfile
- ci/ubuntu20.04.dockerfile
- ci/ubuntu21.04.dockerfile
- ci/ubuntu21.10.dockerfile
- test_workloads.py
In this commit, following changes are introduced:
1. Port address whether in use, is checked for nginx workload.
2. Sandstone workload is pushed at last, so that it will be
executed after the examples. Also, pytest markers are used for
examples and sandstone.
> CI improvements for Sandstone and Nginx

- tf_parser.py
The parser for TF is updated for different string in output format
for BERT and RESNET.
> Updating TF parser

- ci/stage-test-examples.jenkinsfile
- ci/stage-test.jenkinsfile
- ltp_config/manifest_CentOS_RHEL.template
The manifest files for above mentioned configurations are updated
following new regressions.
> Update Cent/RHEL and LibOS suite's manifest files

- ci/debian11.dockerfile
- ci/linux_pkg-deb.jenkinsfile
- ci/pkg_deb.jenkinsfile
- test_workloads.py
http://ba5sapp0350:8080/view/Graphene/job/graphene_pkg_deb/37/
> Enable CI Examples for debian verification

- ltp_config/ltp_tests.cfg
The config file for LTP is updated corresponding to the commit
"Completely rewrite networking code".
> Update LTP config

- Patch/rename_protected_file.patch
- Python/Makefile
- Python/python.manifest.template
- ci/config/config-docker.jenkinsfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/lib/stage-test.jenkinsfile
- ci/resources/setup_workspace.sh
The changes are corresponding to commits, "Lowercase directory names"
and "Introduce sgx.remote_attestation = "[none|epid|dcap]""
> EPID for Python and LibOS suite and lowercase format

- ci/dockerfile/centos8.dockerfile
- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu21.04.dockerfile
- ci/dockerfile/ubuntu21.10.dockerfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
The changes are corresponding to above mentioned commit.
> Update benchmark-http.sh script to use wrk2 benchmark

- ci/dockerfile/centos8.dockerfile
- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu21.04.dockerfile
- ci/dockerfile/ubuntu21.10.dockerfile
- test_workloads.py
Parser Verification Update:
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/113/testReport/
> Add bc to dockerfile and update parser

- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/resources/setup_workspace.sh
The output statements for Python are displayed and issue for RHEL
with gramine-direct is fixed.
> Changes corresponding to renaming and Python

- Patch/rename_protected_file.patch
- ci/lib/stage-test-sgx.jenkinsfile
In this commit, Python is also enabled for Ubuntu 21.10.
> Update patch for FS testcase after recent renaming at Gramine core

- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu21.04.dockerfile
- ci/dockerfile/ubuntu21.10.dockerfile
http://ba5sapp0350:8080/view/Graphene/job/sumedha_test_pipeline/4/testReport/
> Updating the docker files with "protobuf-compiler"

- Patch/rename_protected_file.patch
- ltp_src/testcases/kernel/syscalls/bind/bind01.c
PR bind01/FS
20.04 SGX http://ba5sapp0350:8080/view/Graphene/job/z_test_new/12/testReport/
> Updating bind01 testcase and FS patch

- gsc/templates/ubuntu/Dockerfile.build.template
- gsc/templates/ubuntu/Dockerfile.compile.template
The changes are corresponding to commit
"Build GSC with -Ddcap=enabled by default"
> GSC changes corresponding to recent commit

- ci/lib/stage-test-examples.jenkinsfile
Increased the timeout for tensorflow-lite in order to test if it resolves the timeout issue.
> Increased the timeout for tensorflow-lite

- ltp_src/testcases/kernel/syscalls/statvfs/statvfs02_run.c
- ltp_src/testcases/kernel/syscalls/statvfs/statvfs02_setup.c
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/127/testReport/
> Update the tmp path to resolve conflict

- ci/config/config-docker.jenkinsfile
- ci/lib/stage-build-perf.jenkinsfile
- ci/lib/stage-redis-perf.jenkinsfile
- ci/lib/stage-tf-bert-perf.jenkinsfile
- ci/lib/stage-tf-resnet-perf.jenkinsfile
- ci/linux-perf-redis.jenkinsfile
- ci/linux-perf-tf-bert.jenkinsfile
- ci/linux-perf-tf-resnet.jenkinsfile
- ci/resources/tf_parser.py
- perf_benchmarking/bert/Makefile
- perf_benchmarking/bert/python.manifest.template
- perf_benchmarking/bert/start_benchmark.sh
- perf_benchmarking/redis/redis_client_scripts/Readme.txt
- perf_benchmarking/redis/redis_client_scripts/instance_benchmark.sh
- perf_benchmarking/redis/redis_client_scripts/start_benchamark.sh
- perf_benchmarking/redis/redis_server_scripts/Readme.txt
- perf_benchmarking/redis/redis_server_scripts/parser.py
- perf_benchmarking/redis/redis_server_scripts/redis-server.manifest.template
- perf_benchmarking/redis/redis_server_scripts/redis-server.manifest.template.exitless
- perf_benchmarking/redis/redis_server_scripts/redis_launch.py
- perf_benchmarking/resnet/Makefile
- perf_benchmarking/resnet/python.manifest.template
- perf_benchmarking/resnet/start_benchmark.sh
Tested in Jenkins:
http://ba5sapp0350:8080/job/local_ci_graphene_perf_redis/366/
http://ba5sapp0350:8080/job/local_ci_graphene_perf_bert/168/
http://ba5sapp0350:8080/job/local_ci_graphene_perf_resnet/148/
> Enabling Perf benchmarking for Redis and Tensorflow

- ci/lib/stage-test-gsc-python.jenkinsfile
- ci/lib/stage-test-gsc.jenkinsfile
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_gsc_18.04/693/
> Enabling no-cache for gsc build

- Python/python.manifest.template
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/resources/setup_workspace.sh
Increased the enclave size and number of threads in order to resolve the memory mapping issue of python and pytorch
> Increased the enclave size and number of threads

- ci/lib/stage-test-examples.jenkinsfile
- ltp_config/ltp_tests.cfg
- ltp_config/test_ltp.py
- ltp_src/testcases/kernel/syscalls/bind/bind01.c
- test_workloads.py
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/129/console
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/98/console
> Fix up local ci failure cases

- ltp_src/testcases/kernel/syscalls/statvfs/statvfs02_setup.c
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_rhel_client/62/testReport/
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_rhel_client/63/testReport/
> Cleaning up statvfs file for jobs running on baremetal

- ci/lib/stage-test-examples.jenkinsfile
- ci/resources/setup_workspace.sh
- test_workloads.py
http://ba5sapp0350:8080/job/local_ci_graphene_sgx_oot/471/
> Enabling  CI examples for OOT driver

- ci/lib/stage-test.jenkinsfile
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_rhel_client/65/testReport/libos.test.regression.test_libos/TC_01_Bootstrap/test___test_212_shebang_test_script/
> Adding libtinfo also for shebang_test_script manifest

- ci/lib/stage-test-examples.jenkinsfile
- stress-ng/Makefile
Resolved the following issues for rhel server.
-Pytorch
-rust
-stree-ng
-gcc
> Resolve issues in RHEL server

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/centos8.dockerfile
- ci/dockerfile/common_centos.dockerfile
- ci/dockerfile/common_ubuntu.dockerfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-clone.jenkinsfile
- ci/lib/stage-test-sanity.jenkinsfile
- ci/linux-sgx-common-gcc-release.jenkinsfile
http://ba5sapp0350:8080/view/Graphene/job/local_ci_gsgx_package/117/console
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/100/testReport/
> Enable Package verification and test helloworld example

- ci/lib/stage-clone.jenkinsfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/resources/setup_ltp.sh
- ci/resources/setup_workspace.sh
- ltp_config/ltp-bug-1075_tests.cfg
- ltp_config/ltp_skip-tests.cfg
- ltp_config/ltp_tests.cfg
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_centos/47/testReport/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/142/testReport/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/102/console
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/143/testReport/
> Updating ltp test config

- ci/dockerfile/common_centos.dockerfile
- ci/dockerfile/common_ubuntu.dockerfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-clone.jenkinsfile
- ci/lib/stage-test-sanity.jenkinsfile
- ci/linux-sgx-common-gcc-release.jenkinsfile
- test_workloads.py
graphene_18.04: http://ba5sapp0350:8080/view/Graphene/job/local_ci_gsgx_package/181/console
graphene_dcap: http://ba5sapp0350:8080/view/Graphene/job/local_ci_gsgx_package/182/console
graphene_oot: http://ba5sapp0350:8080/view/Graphene/job/local_ci_gsgx_package/183/console
graphene_centos: http://ba5sapp0350:8080/view/Graphene/job/local_ci_gsgx_package/184/console
> Adding RA-TLS examples to package verification

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/common_centos.dockerfile
- ci/dockerfile/common_ubuntu.dockerfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-clone.jenkinsfile
- ci/lib/stage-test-sanity.jenkinsfile
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/26/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/27/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/28/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/29/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/30/
> Updating the packages

- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
local_ci_graphene_sgx_oot : http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/19/consoleFull
local_ci_graphene_sgx_20.04_5.17 : http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/12/consoleFull
> Disabling Pytorch and gcc to run on sgx oot

- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- test_workloads.py
Enabled ra-tls-mbedtls and ra-tls-secret-prov to sgx dcap.
http://ba5sapp0350:8080/job/sumedha_graphene_sgx_job/33/consoleFull
> Added ra-tls-mbedtls and ra-tls-secret-prov to stage test examples

- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/pkg_deb.jenkinsfile
- perf_benchmarking/bert/python.manifest.template
- perf_benchmarking/resnet/python.manifest.template
- stress-ng/stress-ng.manifest.template
Centos: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/38/
Rhel: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_sgx_rhel_server/1/
> Removing loader.pal_internal_mem_size option.

- ltp_config/ltp-bug-1075_tests.cfg
- ltp_config/ltp-sgx_centos_tests.cfg
- ltp_config/ltp-sgx_skip-tests.cfg
- ltp_config/ltp-sgx_tests.cfg
- ltp_config/ltp_tests.cfg
Native job : http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_native_job/1/consoleFull
sgx_20.04_5.17: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/40/testReport/libos.test.ltp/test_ltp/
centos : http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/41/testReport/libos.test.ltp/test_ltp/
> Enabled LTP tests

- ci/config/config-docker.jenkinsfile
- ci/lib/stage-build-sgx.jenkinsfile
Unstable Package: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/72/
> Adding Debian frontend to non interactive for Gramine installation

- ltp_config/ltp-bug-1075_tests.cfg
- ltp_config/ltp-sgx_tests.cfg
- ltp_config/ltp_tests.cfg
- ltp_src/testcases/kernel/syscalls/mmap/mmap001.c
- ltp_src/testcases/kernel/syscalls/mmap/mmap01.c
- ltp_src/testcases/kernel/syscalls/msync/msync03.c
graphene_sgx_job: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/45/testReport/
graphene_native_job: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_native_job/7/testReport/
centos: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_centos/3/testReport/
> Enabling LTP testcases for direct, sgx and centos

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu21.04.dockerfile
- ci/dockerfile/ubuntu21.10.dockerfile
- ci/dockerfile/ubuntu22.04.dockerfile
- ci/lib/stage-build-nosgx.jenkinsfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- gsc/templates/debian/Dockerfile.build.template
- gsc/templates/debian/Dockerfile.compile.template
- test_workloads.py
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_dcap/504/testReport/test_workloads/Test_Workload_Results/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/153/testReport/test_workloads/Test_Workload_Results/verification___test_python_workload/
> Enable DCAP attestation for Python example

- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test.jenkinsfile
- test_workloads.py
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_22.04_5.18/24/
OOT http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/46/consoleFull
> Changing node_label from graphene_oot to graphene_22.04_5.18

- ci/lib/stage-test-sgx.jenkinsfile
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/51/testReport/
> Check if compiler didn't emit syscall in any of libcs

- ltp_config/ltp-bug-1075_tests.cfg
- ltp_config/ltp_tests.cfg
Ran CI jobs for native and sgx
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_native_job/18/testReport/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/53/testReport/libos.test.ltp/test_ltp/
> Enable Ltp test case [ppoll01] and disable [personality02]

- ci/lib/stage-build-gsc.jenkinsfile
- ci/lib/stage-test-gsc.jenkinsfile
- ci/linux-sgx-gsc-release.jenkinsfile
- gsc/test/centos8-bash.manifest
- gsc/test/centos8-helloworld.dockerfile
- gsc/test/ubuntu18.04-bash.dockerfile
- gsc/test/ubuntu18.04-bash.manifest
- gsc/test/ubuntu20.04-bash.dockerfile
- gsc/test/ubuntu20.04-bash.manifest
**Ubuntu 18.04:** http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/19/
**Ubuntu 20.04:** http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/20/
**Centos 8:** http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/22/
> Updating gsc tests

- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
logs :
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_native_job/19/consoleFull
> Increased Timeout for blender example

- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu22.04.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/resources/setup_workspace.sh
- test_workloads.py
- utils/tfserving/Makefile
- utils/tfserving/tensorflow_model_server.manifest.template
ubuntu 20.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/290/console
centos 8: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/282/console
ubuntu 22.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/288/consoleFull
ubuntu 18.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/285/consoleFull
> Adding Scikit and Tensorflow serving example into local ci

- ci/dockerfile/common_ubuntu.dockerfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-clone.jenkinsfile
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/94/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/95/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/96/
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_package_test_pipeline/97/
> Updating the package as per v1.4

- ci/lib/stage-build-sgx.jenkinsfile
- ci/linux-sgx-build-without-prefix-sanity.jenkinsfile
- ci/linux-sgx-gcc-release-sanity.jenkinsfile
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_build_without_prefix/6/
> Building without prefix

- ci/dockerfile/debian11.dockerfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/resources/setup_ltp.sh
- ltp_config/manifest_Debian_11.template
- test_workloads.py
**Debian11 OS** and Kernel v 6.0.0-0.deb11.6-amd64 are added to Nightly Pipeline and tested successfully.
below are the console logs for the native and SGX runs, 
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_native_debian_6.0/654/consoleFull
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_debian_6.0/580/console
> Adding support for debian os

- ci/lib/stage-test-examples.jenkinsfile
fixed catch block - 
Test execution logs can be found on below link - 
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_native_18.04_5.19/125/console
> trycatch fix -tensorflow example

- ci/dockerfile/almalinux9.dockerfile
- ci/lib/stage-build-nosgx.jenkinsfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/lib/stage-test.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- ci/resources/setup_ltp.sh
- test_workloads.py
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/173/console
> Adding support for almalinux

- ci/config/config-docker.jenkinsfile
- ci/lib/stage-build-nosgx.jenkinsfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/lib/stage-test.jenkinsfile
- pipelines/gramine_build_without_prefix_pipeline
- pipelines/graphene_nightly_edmm_pipeline
- pipelines/graphene_nightly_pipeline
SGX
ubuntu    -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/328/
dcap      -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/325/
oot       -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/324/
almalinux -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/326/
debian    -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/327/
centos    -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/329/
Native
ubuntu    -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/175
almalinux -> http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/176
> Simplify SGX Build and add pipelines into git

- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test.jenkinsfile
**SGX**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/336/consoleFull
**Native**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/177/console
**W/O Prefix:** http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_build_without_prefix/157/console
> Fix sanity pipeline and almalinux test

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/rockylinux9.dockerfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- ci/resources/setup_ltp.sh
- pipelines/graphene_nightly_pipeline
- test_workloads.py
test successfully completed for the Rocky Linux v9 with kernel version 6.2.0
below are the console logs for the executions.
native :
http://ba5sapp0350:8080/job/nakul_native_rockylinux/8/console
SGX:
http://ba5sapp0350:8080/job/nakul_rockylinux_sgx/4/console
> added support for RockyLinux

- Patch/rename_protected_file.patch
- ci/dockerfile/ubuntu18.04.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ltp_config/manifest_18_04.template
- ltp_config/manifest_20_04_21_10.template
- ltp_config/manifest_Almalinux.template
- ltp_config/manifest_CentOS.template
- ltp_config/manifest_Debian_11.template
- ltp_config/manifest_RHEL.template
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_centos_6.0/566/consoleFull
> Fix local CI issue

- ci/dockerfile/centos8.dockerfile
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/344/console
> Changing docker image from centos to centos stream

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/centos9.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- ci/resources/setup_workspace.sh
- pipelines/graphene_nightly_pipeline
- utils/time_sync_helper.py
Native and SGX gramine runs successfully tested with Centos stream9 - 
Native -
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/nakul_native_centos9/4/console
SGX - 
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/nakul_sgx_centos9/1/console
> adding centos stream 9 support

- utils/time_sync_helper.py
This PR to add functionality of setting time zone.
Default Asia/Kolakata timezone will be set for the systems.
> added timezone set function

- ci/dockerfile/centos9.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
Minor fixes for centos9.
SGX run:
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/nakul_sgx_centos9/4/consoleFull
> improved stream9 support

- ci/dockerfile/centos8.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
Check for docker build & CI-Examples/rust
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/198/consoleFull
> Installing Rust libraries from dockerfile

- ci/config/config-alpine.jenkinsfile
- ci/config/config-centos8.jenkinsfile
- ci/config/config-docker.jenkinsfile
- ci/dockerfile/alpine3.18.dockerfile
- ci/lib/stage-build-nosgx.jenkinsfile
- ci/lib/stage-build-sgx-vm.jenkinsfile
- ci/lib/stage-build-sgx.jenkinsfile
- ci/lib/stage-test-direct.jenkinsfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/lib/stage-test.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- ci/resources/setup_alpine.sh
- ci/resources/setup_workspace.sh
- test_workloads.py
Gramine-Direct
Alpine: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/311/testReport/
Ubuntu 22.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/312/consoleFull
Gramine-SGX
Alpine: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/397/console
CentOS: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/401/console
> Integrating Alpine into local ci

- ci/lib/stage-test-sanity.jenkinsfile
- ci/linux-sgx-common-gcc-release.jenkinsfile
- pipelines/gramine_package_pipeline
- verify_package_version.py
Ubuntu20.04: http://ba5sapp0350:8080/job/jinen_package_testing/28/console
Ubuntu22.04: http://ba5sapp0350:8080/job/jinen_package_testing/29/console
Debian11: http://ba5sapp0350:8080/job/jinen_package_testing/30/console
stream9: http://ba5sapp0350:8080/job/jinen_package_testing/31/console
stream8: http://ba5sapp0350:8080/job/jinen_package_testing/32/console
> Adding logic to verify package version

- ci/config/config-alpine.jenkinsfile
- ci/config/config-centos8.jenkinsfile
- ci/config/config-docker.jenkinsfile
- ci/dockerfile/debian12.dockerfile
- test_workloads.py
Debian11: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/63/
Debian12: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/67
CentOS9: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/66
Alpine: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/65
> Fix TF and OpenJDK test for Debian12

- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu22.04.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
Ubuntu20.04: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/97/console
Ubuntu22.04: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/96/console
> Adding MongoDB to local CI

- ci/dockerfile/debian11.dockerfile
- ci/dockerfile/debian12.dockerfile
- ci/dockerfile/rhel8.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu22.04.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/lib/stage-test-stress-ng.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- test_workloads.py
Debian 12: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/417/
Debian 11: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsgx_ubuntu/416/
> Fixing python libraries issues and enabling other workloads

- pipelines/gramine_gsc_pipeline
Local CI test run: http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_gsc_debian_11/237/
> Add Debian12 pipeline for GSC

- ci/dockerfile/centos8.dockerfile
- ci/dockerfile/common_debian.dockerfile
- ci/dockerfile/common_ubuntu.dockerfile
- ci/dockerfile/debian11.dockerfile
- ci/dockerfile/debian12.dockerfile
- ci/dockerfile/ubuntu20.04.dockerfile
- ci/dockerfile/ubuntu22.04.dockerfile
Some fails because of update requires y/n
> Adding -y flag to update

- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
Moving tfserving to the end, because of apt update failing causing mongodb failure and combined all server tests
> Moving tfserving to end and combine server tests

- pipelines/gramine_gsc_pipeline
http://ba5sapp0350:8080/view/Graphene/job/gramine_gsc_pipeline/106/console
I have created a single pipeline for all gsc distros
> Adding UBI8, UBI8-Minimal and Ubuntu 23.04 to gsc pipeline

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/common_ubi.dockerfile
- ci/linux-sgx-common-gcc-release.jenkinsfile
- ci/resources/setup_pkg.sh
- pipelines/gramine_package_pipeline
http://ba5sapp0350:8080/view/Graphene/job/gramine_package_pipeline/12/console
> Add RHEL8/RHEL9 package validation

- ci/dockerfile/almalinux9.dockerfile
- ci/dockerfile/centos8.dockerfile
- ci/dockerfile/centos9.dockerfile
- ci/dockerfile/rhel8.dockerfile
- ci/dockerfile/rhel9.dockerfile
- ci/dockerfile/rockylinux9.dockerfile
- ci/lib/stage-test-sgx.jenkinsfile
- test_workloads.py
Debian12: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/112/parameters/
Rhel9: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/117/parameters/
Ubuntu20.04: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/118/parameters/
> Enable memcached for Debian and RPM based distros

- ci/lib/stage-clone.jenkinsfile
- ci/lib/stage-test-sgx.jenkinsfile
- ci/linux-direct-gcc-release.jenkinsfile
- ci/linux-sgx-gcc-release.jenkinsfile
- ltp_config/manifest_20_04_21_10.template
- ltp_config/manifest_Almalinux.template
- ltp_config/manifest_CentOS.template
- ltp_config/manifest_Debian_11.template
- ltp_config/manifest_RHEL.template
- pipelines/graphene_nightly_pipeline
Creating a Temp commit, will delete it later
> Testing Dynamic EDMM PR

- ci/lib/stage-build-gsc.jenkinsfile
- ci/lib/stage-test-gsc.jenkinsfile
- test_workloads.py
http://ba5sapp0350:8080/job/jinen_gsc_test_job/15/console
> Add new test for running GSC with build-gramine option

- ci/linux-sgx-gcc-release.jenkinsfile
- ci/resources/setup_workspace.sh
- ltp_config/manifest_20_04_21_10.template
- ltp_config/manifest_Almalinux.template
- ltp_config/manifest_CentOS.template
- ltp_config/manifest_Debian_11.template
- ltp_config/manifest_RHEL.template
- pipelines/graphene_nightly_pipeline
This reverts commit 5d71f809fd6c510a5c272c8b6dfc0f1a9d5d5d71.
> Revert "Testing PR 1570"

- ci/dockerfile/rhel8.dockerfile
- ci/dockerfile/rhel9.dockerfile
- pipelines/gramine_stressng_pipeline
Native run for RHEL8: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/119/consoleFull
> Enable stress-ng for RHEL8

- ci/dockerfile/debian12.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
> Fix for Debian 12 file issue and mongodb wait

- ci/lib/stage-test-examples.jenkinsfile
EDMM RHEL: http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_rhel_server_6.2/1589/consoleFull
@sreeharikax
> Increasing wait for iperf

- ltp_config/ltp_tests.cfg
- ltp_config/test_ltp.py
- ltp_src/testcases/kernel/syscalls/getcpu/getcpu01.c
select01 and clockgettime01 will require further debugging, hence not addressed as part of this PR
> Fix LTP Upgrade issues

- ci/lib/stage-test-stress-ng.jenkinsfile
- stress-ng/tests_stressng.py
RHEL Native: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gnative_ubuntu/335/console
Verification condition updated
> Skip seek test for RHEL Native

- ci/dockerfile/alpine3.18.dockerfile
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_native_alpine_3.18_6.1/269/consoleFull
> Removing EDGE repos from Alpine container

- ci/config/config-docker.jenkinsfile
- ci/dockerfile/ubuntu24.04.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- ci/resources/setup_ltp.sh
- pipelines/gramine_build_without_prefix_pipeline
- pipelines/gramine_sdtest_pipeline
- pipelines/gramine_stressng_pipeline
- pipelines/graphene_nightly_edmm_pipeline
- pipelines/graphene_nightly_pipeline
- test_workloads.py
http://ba5sapp0350:8080/job/harika_local_ci_test_job/84/
> Enabled ubuntu 24.04 distro support in graphene nightly pipeline.

- ci/lib/stage-clone.jenkinsfile
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/141/
Gramine Branch: v1.7-ITP
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/140/
Gramine Branch: dimakuv/prot_refresh_mmaped-refactor
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/139/
Gramine Branch: v1.7_update
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/138/
Gramine URL: https://github.com/kailun-qin/gramine.git
Gramine Branch: kailun-qin/glibc-2.40
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/137/
Gramine URL: https://github.com/kailun-qin/gramine.git
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/136/
Gramine Branch: v1.7
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_1/133/
> Updating gramine clone logic to support printing commit

- ci/lib/stage-build-gsc.jenkinsfile
- pipelines/gramine_gsc_pipeline
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/101/consoleFull
> Added ubuntu 24.04 gsc job with venv

- ci/lib/stage-build-gsc.jenkinsfile
- gsc/test/setup.sh
- gsc/test/suse-bash.dockerfile
- gsc/test/suse-helloworld.dockerfile
- pipelines/gramine_gsc_pipeline
http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/harika_gsc_test_job/163/console
> Integrate openSUSE to graphene_local_ci in gsc pipeline.

- ci/lib/stage-build-gsc.jenkinsfile
http://ba5sapp0350:8080/job/anjali_gsc_test_job/103/
> Removed virtual environment for ubuntu24.04 distro

- ci/lib/stage-test-examples.jenkinsfile
- pipelines/gramine_package_pipeline
http://ba5sapp0350:8080/job/local_ci_graphene_native_22.04_5.19/656/testReport/
> VM Map Count and Ubuntu 24.04 DCAP fix

- utils/tfserving/Makefile
http://ba5sapp0350:8080/job/harika_local_ci_test_job/130/
> Updated tfserving version

- ci/lib/stage-build-gsc.jenkinsfile
- ci/linux-sgx-gsc-release.jenkinsfile
- pipelines/gramine_gsc_pipeline
http://ba5sapp0350:8080/view/Graphene/job/test_gsc_pipeline/1/console
> Add PR support to gsc

- ci/lib/stage-test-gsc.jenkinsfile
- test_workloads.py
http://ba5sapp0350:8080/view/Graphene/job/temp_local_ci_graphene_gsc/9/console
> Add tests for Gramine-Direct in GSC

- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
- workloads/mariadb/Makefile
- workloads/mariadb/README.md
- workloads/mariadb/mysqld.manifest.template
Mariadb Enablement for Ubuntu, Rhel and Centos
> Mariadb Support

- Patch/rename_protected_file.patch
- ci/dockerfile/centos9.dockerfile
- ci/dockerfile/rhel9.dockerfile
- ci/lib/stage-test-examples.jenkinsfile
- test_workloads.py
**Native:**
centos9: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_native_pipeline/18/
ubuntu22.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_native_pipeline/17/
**SGX:**
rhel9: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_sgx_pipeline/17/
ubuntu24.04: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/test_sgx_pipeline/16/
> Venv and Mariadb fix

- ci/lib/stage-build-gsc.jenkinsfile
- ci/lib/stage-test-gsc.jenkinsfile
- ci/linux-sgx-gsc-release.jenkinsfile
- gsc/verifier/helper.sh
http://10.99.116.103:8080/view/Old%20Graphene%20Jobs/job/local_ci_graphene_gsc_test/1/consoleFull
> Update verifier helper script

- ci/lib/stage-test-examples.jenkinsfile
Modification with respect to latest pytorch in examples repo
> Modification with respect to latest pytorch in examples repo

- ci/lib/stage-build-gsc.jenkinsfile
- test_workloads.py
> updated debian distro and tested examples (Java-simple & java-spring-boot)
