ci/stage-test-sgx.jenkinsfile

In this commit, the number of threads and enclave size is based on the number of processing units

Fixing "Blender" example issue regarding number of threads and enclave size

---

ci/stage-test-direct.jenkinsfile
ci/stage-test-sgx.jenkinsfile

In this commit, the ARCH_LIBDIR option which is
required for x86_64-redhat-linux machines, is added

Adding the ARCH_LIBDIR option for CentOS

---

ci/stage-test-sgx.jenkinsfile

In this commit, the issue is resolved by putting single quotes instead of double quotes.

Fix for 'sed' command issue in "Blender"

---

ltp_config/runltp_tests.py

In this commit, the read ELF header error is bypassed, if the required testcases are executed successfully

Bypassing  the execve03 error issue due to read ELF header

---

ltp_config/runltp_tests.py

In this commit, the disallowing access error message is bypassed if all the testcases are executed successfully.

Bypassing disallowing access error message for clock_gettime04

---

ci/stage-test-direct.jenkinsfile
ci/stage-test-sgx.jenkinsfile

In this commit, the above mentioned examples are excluded from pipeline for "x86_64-redhat-linux" machines

Excluding "GCC" and "Memcached" example for "x86_64-redhat-linux"

---

ltp_config/runltp_tests.py

In this commit, the error regarding "Detected deprecated syntax" is bypassed.

Bypassing error message

---

ci/stage-test-sgx.jenkinsfile
ltp_config/ltp_tests.cfg

In this commit, the PAL internal memory size is allocated as per the requirement for CentOS and RHEL machines. The four testcases with must pass conditions are removed from config file.

PAL internal memory allocation and removal of must pass condition

---

ci/linux-direct-centos8.2-gcc-release.jenkinsfile
ci/linux-direct-ubuntu18.04-gcc-release.jenkinsfile
ci/linux-direct-ubuntu20.04-gcc-release.jenkinsfile
ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu18.04-gcc-release-apps.jenkinsfile
ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu18.04-stress-ng.jenkinsfile
ci/linux-sgx-ubuntu20.04-gcc-release-apps.jenkinsfile
ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
ci/stage-test-direct.jenkinsfile
ci/stage-test-sandstone.jenkinsfile
ci/stage-test-sgx.jenkinsfile
ci/stage-test-stress-ng.jenkinsfile
ci/ubuntu18.04.dockerfile
ci/ubuntu20.04.dockerfile
ltp_config/ltp_tests.cfg
test_workloads.py

In this commit, "Examples" folder is renamed to CI-Examples.
The examples curl, gcc, apache and R are removed.
SQLite example is added. mkdir09 is skipped in ltp_tests.cfg

Renaming "Examples", remove and add Examples and skip mkdir09 TC

---

ci/stage-test.jenkinsfile

In this commit, the large_mmap TC is skipped as the machine doesn't have sufficient memory.

Skipping the TC "large_mmap" in LibOS for DCAP

---

ci/config-docker.jenkinsfile

In this commit, the cpu_dma_latency is mounted in dockerfile for 5.12 kernel issues

Mounting device "cpu_dma_latency" for docker build

---

ltp_config/runltp_tests.py

In this commit, the warning message is bypassed for the parser.

Bypassing warning message in parser

---

ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile

In this commit, cpu_dmalatency is mounted for Ubuntu 18.04 on DCAP machine

Adding sed commands to mount cpu_dmalatency for DCAP

---

ltp_config/runltp_tests.py

In this commit, the error message for disallowing libnss_nis.so.2 file is bypassed.

Bypassing disallow file message for libnss

---

ltp_config/runltp_tests.py

In this commit, the parser is updated corresponding to message displayed on using insecure manifest options.

Uniform message on using insecure manifest options

---

ci/stage-test.jenkinsfile

In this commit, gramine-test has been added for PAL, LIBOS and FS.

Adding gramine-test for PAL, LIBOS and FS

---

ci/stage-test.jenkinsfile

In this commit, the testcase 'large_mmap' is skipped for DCAP in LibOS suite compiled with musl.

Excluding 'large_mmap' for DCAP in LibOS with musl

---

ci/stage-test-direct.jenkinsfile

In this commit, "-n4" option is removed for LTP with direct, as it is not supported on CentOS machines

Removing -n4 option

---

ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
ltp_config/manifest.LTP
ltp_config/manifest.template

In this commit, the libtinfo is added via sed command in manifest file of LTP specifically for CentOS docker.

Adding libtinfo specifically for CentOS docker configuration

---

ltp_config/ltp_tests.cfg

In this commit, the above mentioned file is changed corresponding to commit "[LibOS] Re-map tainted shared file-backed memory regions on fork".

Updating ltp_tests.cfg

---

ltp_config/ltp-sgx_tests.cfg

In this commit, the must pass condition is added for LTP testcases, i.e. execl01, execlp01, execv01 and execvp01 as the TBROK errors were fixed for gramine-direct and not for SGX with the commit "[LibOS] Re-map tainted shared file-backed memory regions on fork".

Adding the must pass condition for failing LTP testcases with SGX

---

ltp_config/ltp_tests.cfg

In this commit, fstat03 is enabled after the fix for internal memory issue with must pass all for gramine-direct.

Enabling fstat03

---

ci/stage-test-sgx.jenkinsfile

In this commit, the timeout for sandstone is increased to 120.

Increasing Sandstone timeout

---

gsc/test/centos8-bash.dockerfile
ltp_config/ltp-sgx_tests.cfg
ltp_config/ltp_tests.cfg
ltp_src/testcases/kernel/syscalls/epoll_pwait/epoll_pwait.h
ltp_src/testcases/kernel/syscalls/epoll_pwait/epoll_pwait01.c

In this commit, following changes are carried out for LTP:
1. pause02 and pause03 are skipped for G-Direct and GSGX.
2. qmm01, mmap09, msync03 and mincore01 are skipped for SGX.
3. epoll_pwait01 is restored from old LTP suite.
In addition, "dmz" proxy is used for CentOS GSC.

Changes to LTP suite and proxy for GSC CentOS configuration

---

ltp_config/ltp-sgx_tests.cfg
ltp_config/ltp_tests.cfg
ltp_config/manifest.template
ltp_config/test_ltp.py

In this commit, following changes are done:
1. Increase timeout of getpid01.
2. Pass for TBROK issue for SGX in case of getpid01 and getppid02.
3. Skip select03 for gramine-direct and gramine-sgx.
4. Files required for pipe2_02 are added in trusted SGX section.

SGX TBROK change, pipe2_02 and select03

---

ltp_config/test_ltp.py

In this commit, the split on standard error output is based on "error:" and the error message "Detected deprecated syntax" is
allowed.

Updating LTP parser for standard output

---

stress-ng/Makefile
stress-ng/stress-ng.manifest.template

In this commit, manifest file for stress-ng is updated as per the new format and manifest file is updated to use 
gramine-sgx-gen-private-key.

Updating stress-ng Makefile and manifest file.

---

rust_helloworld/hello.manifest.template
stress-ng/stress-ng.manifest.template

In this commit, loader.preload is removed from Rust and stress-ng.

Drop support for loader.preload in manifests

---

ci/stage-build-nosgx.jenkinsfile
ci/stage-build-sgx.jenkinsfile
ltp_config/test_ltp.py

In this commit, error message for IPC and bind01 testcase is bypassed and werror is enabled in Gramine building steps with meson.

Bypassing bind01 and IPC error message and enabling werror

---

ltp_config/ltp-sgx_tests.cfg
ltp_config/ltp_tests.cfg

In this commit, fsync03 is enabled following the commit "[LibOS] Make fsync() and fdatasync() a no-op on dirs"

Enabling fsync03

---

tf_parser.py

In this commit, gramine-direct is enabled for TF workloads.

Enabling gramine-direct for TF workloads

---

ci/centos8.dockerfile
ci/stage-test.jenkinsfile
ci/ubuntu18.04.dockerfile
ci/ubuntu20.04.dockerfile
ci/ubuntu21.04.dockerfile
ci/ubuntu21.10.dockerfile
gsc/templates/centos/Dockerfile.compile.template
gsc/templates/ubuntu/Dockerfile.compile.template

In this commit, nasm is added to dockerfiles and tests for Application binary Interface (ABI) for x86_64 are also enabled.

Add nasm to meson and tests for ABI

---

ci/stage-test-direct.jenkinsfile
ci/stage-test-sgx.jenkinsfile
ltp_config/manifest_18_04.template
ltp_config/manifest_20_04_21_10.template
ltp_config/manifest_CentOS_RHEL.template

In this commit, debug mode is set for python example. Also, the error log is archived. The sysfs feature is disabled for LTP suite as per the recent commit.

Enabling debug mode for Python example

---

Patch/rename_protected_file.patch
ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
ci/linux-sgx-centos8.2-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu18.04-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu20.04-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu21.04-gcc-release.jenkinsfile
ci/linux-sgx-ubuntu21.10-gcc-release.jenkinsfile
ci/stage-build-sgx.jenkinsfile
ci/stage-test.jenkinsfile

The above mentioned testcase is enabled again for FS suite after
updating the manifest file to new format and changes in assert
statement of the testcase.

Enabling FS suite testcase for renaming of a protected file

---

ltp_config/test_ltp.py

Sets in Python do not have `+` operator, `|` is used for unions.

Fix an incorrect usage of sets in "test_ltp.py"

---

ci/stage-test-direct.jenkinsfile
ci/stage-test-examples.jenkinsfile
ci/stage-test-sgx.jenkinsfile
test_workloads.py

The busybox example is enabled for all the configurations.
The failing examples due to AESM error are skipped for OOT.
Memcached is skipped for Ubuntu 21.10.

Enabling Busybox example and skipping examples for OOT

---

ci/linux-direct-centos8-docker-gcc-release.jenkinsfile
ci/linux-sgx-centos8-docker-gcc-release.jenkinsfile
ci/stage-test-direct.jenkinsfile
ci/stage-test-sgx.jenkinsfile
ltp_config/ltp-sgx_tests.cfg
test_workloads.py

The parser for Bash example is updated to check for command "ls",
which was not supported on CentOS/RHEL earlier.
Also, timeout for getpid01 is increased.

Updating the parser for Bash example

---

ci/stage-test-sgx.jenkinsfile

The enclave size is increased for Bash in core Gramine.

Removing the sed command to increase enclave size for Bash

---

ci/stage-test-direct.jenkinsfile
ci/stage-test-sgx.jenkinsfile
ltp_config/test_ltp.py

This will make CI timestamp each output line of the LTP binary, making
it possible to check whether these are hangs, or just a case of the
tests executing slow enough to time out.

Run timeout-prone tests with unbufferred output for LTP

---

ci/lib/stage-test-examples.jenkinsfile

The timeout for R is increased following recent failures on some
client machines.

Increasing timeout for R

---

ci/lib/stage-test-sgx.jenkinsfile

As the CI machines are not enabled with RA, python test cases are
failing for SGX.
In this commit, we are building python without RA flag.

Disable RA (Remote Attestation) for python example

---

ci/lib/stage-test-sgx.jenkinsfile

The server does not succesfully launch for centos and rhel, increasing the timeout to launch successfully so that workload can execute successfully
http://ba5sapp0350:8080/job/local_ci_graphene_sgx_centos_5.18/469/console

Increase wait time for server to launch successfully

---

ci/lib/stage-test-examples.jenkinsfile
go_helloworld/helloworld.manifest.template
perf_benchmarking/redis/redis_server_scripts/redis-server.manifest.template

Removed loader.argv0_override manifest option and worked on entrypoint changes.
Increased enclave size for pytorch.
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_18.04_5.14/615/testReport/test_workloads/Test_Workload_Results/

Remove loader.argv0_override manifest option.

---

perf_benchmarking/bert/python.manifest.template
perf_benchmarking/resnet/python.manifest.template

Updated the manifest files for bert and resnet to confirm to the new fs.mount format.
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_perf_resnet/167/console

Update manifest files for tf perf

---

Python/python.manifest.template
ci/lib/stage-test-sgx.jenkinsfile
ci/pkg_deb.jenkinsfile
go_helloworld/helloworld.manifest.template
ltp_config/manifest.LTP
ltp_config/manifest_18_04.template
ltp_config/manifest_20_04_21_10.template
ltp_config/manifest_CentOS.template
ltp_config/manifest_RHEL.template
perf_benchmarking/bert/python.manifest.template
perf_benchmarking/redis/redis_server_scripts/redis-server.manifest.template
perf_benchmarking/redis/redis_server_scripts/redis-server.manifest.template.exitless
perf_benchmarking/resnet/python.manifest.template
stress-ng/stress-ng.manifest.template

[local_ci_graphene_sgx_18.04_5.18] http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_graphene_sgx_job/42/consoleFull
[local_ci_graphene_sgx_rhel_client]  http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_rhel/2/
[local_ci_graphene_sgx_centos_5.14]  http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/sumedha_centos/1/

manifest-option names are renamed  from sgx.thread_num to sgx.max_threads

---

ci/config/config-docker.jenkinsfile
ci/lib/stage-build-sgx.jenkinsfile

http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_dcap/498/console

Update Gramine-Dcap build logic. Dcap can be built with in-kernel headers

---

ci/lib/stage-test-examples.jenkinsfile

Enclave size for Tensorflow example is increased.
Please find execution logs as per below,
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_rhel_client/302/console

Increased enclave for Tensorflow-lite

---

pipelines/graphene_nightly_pipeline

Temporarily disabled Jobs for local_ci_graphene_native_18.04_5.19 and local_ci_graphene_sgx_18.04_5.19
Reason for temporary change is - this machine is used by Jitender to run some attestation experiments

Disabling node graphene_18.04_5.19 jobs

---

ci/lib/stage-test-sgx.jenkinsfile

Execution timeout increased to 20 mins for Redis workload. (only for SGX runs)
SGX:
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_sgx_centos_6.0/588/console

redis timeout increased for SGX

---

ci/lib/stage-build-sgx.jenkinsfile

We previously had hack for Ubuntu 22.04 gramine packages repo. Now, it is not needed

Removing the fix for packages for Ubuntu 22.04

---

ci/dockerfile/ubuntu22.04.dockerfile
ltp_config/ltp_tests.cfg

Linux-headers-generic is not available for Ubuntu 22.04 and disabling recvmsg01

Disable recvmsg01 test

---

ci/lib/stage-build-gsc.jenkinsfile
ci/lib/stage-test-gsc.jenkinsfile
ci/linux-sgx-gsc-release.jenkinsfile
gsc/test/centos8-bash.dockerfile
gsc/test/centos8-helloworld.dockerfile
gsc/test/python.dockerfile
gsc/test/setup.sh
test_workloads.py

Currently not adding new distro like RHEL as part of this commit, But build support is there and it will sort out the workloads based on distro
**Ubuntu 20.04**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/85/console
**centos 8**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/83/console
**debian**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/84/console
**ubi8**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/81/console
**ubi8-minimal**: http://ba5sapp0350:8080/view/Old%20Graphene%20Jobs/job/anjali_gsc_test_job/82/console

Adding support for newer distros and sorting workloads based on distros

---

ci/lib/stage-test-examples.jenkinsfile
ci/lib/stage-test-stress-ng.jenkinsfile
test_workloads.py

Openvino was already disabled earlier, recently enabled it, but it is failing with timeout during model download, so reverting back

Enable memcached verification and reducing stress-ng time

---

ci/lib/stage-test-stress-ng.jenkinsfile
stress-ng/interrupt_all.job

Ubuntu20.04 console output: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/107/
Analysis of 4 failing jobs:
interrupt - unexpected memory fault for sigsuspend test.
interrupt_all - commented out the kill test as that fails with IPC error.
filesystem - unexpected memory fault in lease, chdir, lockofd.
filesystem_all - unexpectedmemory fault in locka test. The job couldn't run all the tests so increased the timeout to 30mins.
CentOS runs in progress: http://ba5sapp0350:8080/job/jinen_graphene_sgx_test/108/

Split all stress-ng jobs into different stages

---

ci/lib/stage-test-sgx.jenkinsfile
ci/linux-sgx-gcc-release.jenkinsfile
stress-ng/filesystem.job
stress-ng/filesystem_all.job

Added EDMM=1 for SGX, to support today nightly runs

Fixing max_threads & removing dir from stress-ng

---

ltp_src/testcases/kernel/syscalls/getpid/getpid01.c

With upgraded LTP, timeout specified for individual test is not taking effect, which was causing this test to fail
Latest Logs:
[0.711] /home/bits/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/libos/test/ltp/ltp_src/lib/tst_test.c:1558: TINFO: Timeout per run is 0h 00m 30s
Old Logs:
[0.678] /home/bits/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/libos/test/ltp/ltp_src/lib/tst_test.c:1362: TINFO: Timeout per run is 0h 05m 00s
[gramine_sgx-getpid01.log](https://github.com/jinengandhi-intel/graphene_local_ci/files/14206243/gramine_sgx-getpid01.log)

Fix for getpid issue

---

utils/tfserving/Makefile

Tensorflow Model Server, download has been replaced with direct package installation
http://ba5sapp0350:8080/view/Graphene/job/local_ci_graphene_native_22.04_5.19/447/console

Tfserving installation Update

---

ci/lib/stage-build-gsc.jenkinsfile

Overview:
Added additional error handling in the finally block for failing 22.04 tests
Stable results after multiple validation runs:
Ubuntu:22.04: Pipeline going till verification stage -
[(http://10.99.116.103:8080/job/local_ci_graphene_gsc/3289/console)](http://10.99.116.103:8080/job/local_ci_graphene_gsc/3289/console)
[(http://10.99.116.103:8080/job/local_ci_graphene_gsc/3304/console)](http://10.99.116.103:8080/job/local_ci_graphene_gsc/3304/console)
[(http://10.99.116.103:8080/job/local_ci_graphene_gsc/3306/console)](http://10.99.116.103:8080/job/local_ci_graphene_gsc/3306/console)
Debian:12: Pipeline going till verification stage - 
[(http://10.99.116.103:8080/job/local_ci_graphene_gsc/3292/console)](http://10.99.116.103:8080/job/local_ci_graphene_gsc/3292/console) …

Jenkins Fixes for docker related failures in  Debian12
